//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MemberDetail
    {
        public int MemberID { get; set; }

        [Required(ErrorMessage ="Yeh kon dalega....!!!")]
        [DataType(DataType.CreditCard)]
          
        public string MemberName { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
    
        public virtual PlanDetail PlanDetail { get; set; }
        public virtual SchemeDetail SchemeDetail { get; set; }
    }
}
