//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDetail()
        {
            this.MemberDetails = new HashSet<MemberDetail>();
        }
    
        public int PlanID { get; set; }
        public Nullable<int> PlanDuration { get; set; }
        public string PlanName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberDetail> MemberDetails { get; set; }
    }
}
