//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchemeDetail()
        {
            this.MemberDetails = new HashSet<MemberDetail>();
        }
    
        public int SchemeID { get; set; }
        public string SchemeName { get; set; }
        public Nullable<double> MonthlyFees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberDetail> MemberDetails { get; set; }
    }
}
